//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Accounts = new HashSet<Accounts>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string EncryptedData { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Accounts> Accounts { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
